[build]
rustflags = ["-Z", "threads=8",
 # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[package.metadata.bevy_cli.unstable]
web-multi-threading = true

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-arg=--shared-memory",
    "-C", "link-arg=--max-memory=1073741824",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--export=__wasm_init_tls",
    "-C", "link-arg=--export=__tls_size",
    "-C", "link-arg=--export=__tls_align",
    "-C", "link-arg=--export=__tls_base",
    # Improve performance
    "--cfg", "web_sys_unstable_apis",
    "-Ctarget-feature=+sign-ext,+nontrapping-fptoint",
    # Compile faster
    "-Zshare-generics=y",
    "-Zthreads=8",
]
rustdocflags = [
    # Compile faster
    "-Zshare-generics=y",
    "-Zthreads=8",
]
[unstable]
codegen-backend = true

[profile.'not(cfg(target_os = "macos"))'.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[patch.crates-io]
# bevy_seedling = { git = "https://github.com/CorvusPrudens/bevy_seedling.git", branch = "master" }
# firewheel = { git = "https://github.com/BillyDM/Firewheel.git", branch = "main" }
# firewheel = { git = "https://github.com/BillyDM/Firewheel.git", rev = "fe1566f3677e655d35721e6cdb432db0e82e530e" }
# firewheel-graph = { git = "https://github.com/BillyDM/Firewheel.git", rev = "fe1566f3677e655d35721e6cdb432db0e82e530e" }
# avian3d = { git = "https://github.com/Jondolf/avian.git", branch = "main" }
# avian3d = { path = "../avian/crates/avian3d" }
# bevy = { path = "../bevy" }
# bevy = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
gltf = { git = "https://github.com/gltf-rs/gltf.git", branch = "main" }

# csgrs = { git = "https://github.com/eswartz/csgrs-fork.git", branch = "bevy-0.18", features = ["bevymesh"] }

# bevy_math = { path = "../bevy/crates/bevy_math" }
# bevy_ecs = { path = "../bevy/crates/bevy_ecs" }
# bevy_internal = { path = "../bevy/crates/bevy_internal" }

# bevy_reflect = { path = "../bevy/crates/bevy_reflect" }
# bevy_app = { path = "../bevy/crates/bevy_app" }
# bevy_color = { path = "../bevy/crates/bevy_color" }
# bevy_log = { path = "../bevy/crates/bevy_log" }
# bevy_platform = { path = "../bevy/crates/bevy_platform" }
# bevy_render = { path = "../bevy/crates/bevy_render" }
# bevy_utils = { path = "../bevy/crates/bevy_utils" }

# bevy_asset = { path = "../bevy/crates/bevy_asset" }
# bevy_mesh = { path = "../bevy/crates/bevy_mesh" }
# bevy_image = { path = "../bevy/crates/bevy_image" }
# bevy_text = { path = "../bevy/crates/bevy_text" }
# bevy_shader = { path = "../bevy/crates/bevy_shader" }
# bevy_core_pipeline = { path = "../bevy/crates/bevy_core_pipeline" }
# bevy_camera = { path = "../bevy/crates/bevy_camera" }
# bevy_sprite = { path = "../bevy/crates/bevy_sprite" }
# bevy_picking = { path = "../bevy/crates/bevy_picking" }
# bevy_light = { path = "../bevy/crates/bevy_light" }
# bevy_gizmos = { path = "../bevy/crates/bevy_gizmos" }
# bevy_sprite_render = { path = "../bevy/crates/bevy_sprite_render" }
# bevy_ui = { path = "../bevy/crates/bevy_ui" }
# bevy_ui_render = { path = "../bevy/crates/bevy_ui_render" }
# bevy_pbr = { path = "../bevy/crates/bevy_pbr" }
# bevy_transform = { path = "../bevy/crates/bevy_transform" }
# bevy_window = { path = "../bevy/crates/bevy_window" }
# bevy_input = { path = "../bevy/crates/bevy_input" }
# bevy_input_focus = { path = "../bevy/crates/bevy_input_focus" }
# bevy_winit = { path = "../bevy/crates/bevy_winit" }
# bevy_gltf = { path = "../bevy/crates/bevy_gltf" }
# bevy_tasks = { path = "../bevy/crates/bevy_tasks" }
# bevy_scene = { path = "../bevy/crates/bevy_scene" }
# bevy_remote = { path = "../bevy/crates/bevy_remote" }
# bevy_time = { path = "../bevy/crates/bevy_time" }
# bevy_diagnostic = { path = "../bevy/crates/bevy_diagnostic" }

# bevy_math = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_ecs = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_internal = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }

# bevy_reflect = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_app = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_color = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_log = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_platform = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_render = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_utils = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }

# bevy_asset = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_mesh = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_image = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_text = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_shader = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_core_pipeline = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_camera = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_sprite = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_picking = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_light = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_gizmos = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_sprite_render = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_ui = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_ui_render = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_pbr = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_transform = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_window = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_input = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_input_focus = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_winit = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_gltf = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_tasks = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_scene = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_remote = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_time = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
# bevy_diagnostic = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }

# [patch.'https://github.com/eswartz/eds_bevy_common.git']
# eds_bevy_common = { path = "../eds_bevy_common" }
