[build]
rustflags = ["-Z", "threads=4",
 # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]

[package.metadata.bevy_cli.unstable]
web-multi-threading = true

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-arg=--shared-memory",
    "-C", "link-arg=--max-memory=1073741824",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--export=__wasm_init_tls",
    "-C", "link-arg=--export=__tls_size",
    "-C", "link-arg=--export=__tls_align",
    "-C", "link-arg=--export=__tls_base",
    # Improve performance
    "--cfg", "web_sys_unstable_apis",
    "-Ctarget-feature=+sign-ext,+nontrapping-fptoint",
    # Compile faster
    "-Zshare-generics=y",
    "-Zthreads=8",
]
rustdocflags = [
    # Compile faster
    "-Zshare-generics=y",
    "-Zthreads=4",
]
[unstable]
codegen-backend = true

[profile.'not(cfg(target_os = "macos"))'.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[patch.crates-io]
# bevy_seedling = { git = "https://github.com/CorvusPrudens/bevy_seedling.git", branch = "master" }
# firewheel = { git = "https://github.com/BillyDM/Firewheel.git", branch = "main" }
# firewheel = { git = "https://github.com/BillyDM/Firewheel.git", rev = "fe1566f3677e655d35721e6cdb432db0e82e530e" }
# firewheel-graph = { git = "https://github.com/BillyDM/Firewheel.git", rev = "fe1566f3677e655d35721e6cdb432db0e82e530e" }
avian3d = { git = "https://github.com/Jondolf/avian.git", branch = "main" }
# avian3d = { path = "../avian/crates/avian3d" }
# bevy = { path = "../bevy" }
# bevy = { git = "https://github.com/eswartz/bevy-fork.git", branch = "ejs-0.18" }
gltf = { git = "https://github.com/gltf-rs/gltf.git", branch = "main" }
